name: Build & Deploy to Azure Container Apps

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: "8.0.x"
  IMAGE_NAME: dddcqrs.presentation
  CONTAINER_APP_NAME: ddd-cqrs
  RESOURCE_GROUP: Demo
  AZURE_CONTAINER_REGISTRY: dddcqrsacr

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        testProject:
          - tests/DddCqrs.Application.UnitTests/DddCqrs.Application.UnitTests.csproj
          - tests/DddCqrs.Domain.UnitTests/DddCqrs.Domain.UnitTests.csproj
          - tests/DddCqrs.Architecture.UnitTests/DddCqrs.Architecture.UnitTests.csproj

    steps:
      - name: üßæ Checkout code
        uses: actions/checkout@v4

      - name: ‚öôÔ∏è Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: üì¶ Restore dependencies
        run: dotnet restore DddCqrs.sln

      - name: üõ† Build solution
        run: dotnet build DddCqrs.sln --configuration Release --no-restore

      - name: ‚úÖ Run unit tests
        run: dotnet test ${{ matrix.testProject }} --configuration Release --no-restore --no-build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: üßæ Checkout code
        uses: actions/checkout@v4

      - name: üê≥ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: üîê Log in to Azure Container Registry (ACR)
        uses: docker/login-action@v3
        with:
          registry: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
          username: ${{ secrets.AZURE_REGISTRY_USERNAME }} #az acr credential show --name <registry-name>
          password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

      - name: üì¶ Build and Push Docker Image to ACR
        uses: docker/build-push-action@v6
        with:
          context: .
          file: src/DddCqrs.Presentation/Dockerfile
          push: true
          tags: |
            ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:latest

      - name: üîë Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          # Secrets.AZURE_CREDENTIALS = JSON t·ª´ Azure Service Principal
          # az ad sp create-for-rbac --name "github-actions" --role contributor --scopes /subscriptions/<SUBSCRIPTION_ID> --sdk-auth

      - name: üöÄ Deploy to Azure Container App
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          resourceGroup: ${{ env.RESOURCE_GROUP }}
          containerAppName: ${{ env.CONTAINER_APP_NAME }}
          environmentVariables: |
            ASPNETCORE_ENVIRONMENT=Production
            ConnectionStrings__MyDatabase=secretref:db-conn


